"""Minimal task boundary shared by pipeline generators."""

from __future__ import annotations

from typing import Any, Literal, Protocol


class TaskProtocol(Protocol):
    name: str
    version: str
    objective_sense: Literal["minimize", "maximize"]

    def generate_instance(self, seed: int, **params: Any) -> Any: ...

    def initial_state(self, instance: Any) -> Any: ...

    def legal_actions(self, state: Any) -> tuple[int, ...]: ...

    def apply_action(self, state: Any, action: int) -> Any: ...

    def is_feasible(self, state: Any) -> bool: ...

    def is_terminal(self, state: Any, reference_value: float | None = None) -> bool: ...

    def objective(self, state: Any) -> float: ...

    def is_better(self, candidate: float, incumbent: float) -> bool: ...

    def objective_gap(self, value: float, reference: float, *, epsilon: float = 1e-9) -> float: ...

    def is_success(self, state: Any, reference_value: float | None = None) -> bool: ...

    def serialize_state(self, state: Any) -> dict[str, Any]: ...

    def deserialize_state(self, value: dict[str, Any]) -> Any: ...

    def parse_action(self, text: str) -> int: ...
