"""Minimal task boundary shared by pipeline generators."""

from __future__ import annotations

from typing import Any, Protocol


class TaskProtocol(Protocol):
    name: str
    version: str

    def generate_instance(self, seed: int, **params: Any) -> Any: ...

    def initial_state(self, instance: Any) -> Any: ...

    def legal_actions(self, state: Any) -> tuple[int, ...]: ...

    def apply_action(self, state: Any, action: int) -> Any: ...

    def is_feasible(self, state: Any) -> bool: ...

    def is_terminal(self, state: Any) -> bool: ...

    def objective(self, state: Any) -> float: ...

    def serialize_state(self, state: Any) -> dict[str, Any]: ...

    def parse_action(self, text: str) -> int: ...
